### ISSUE TITLE
Setup blogs 

### ISSUE THREAD

**Issue by litvintech** [cybercongress/congress#5]

**Comment by SaveTheAles** [comment]
1. Create an account on reddit.com . Can't create a community for 30 days. [that's why](https://www.reddithelp.com/en/categories/using-reddit/creating-subreddits/how-do-i-create-community)
2. Create an account on medium.com. Ask them support about community account. 
3. Telegram supergroup has been created by @21xhipster . Do we need a channel? 
4. Create an community [account](https://twitter.com/congress_cyber) on twitter.
5. Do we need an youtube channel or events it's OK?
6. What about Steemit and Golos?

**Comment by 21xhipster** [comment]
Until keys from blogs will not be in our pockets an issue remains open

**Comment by litvintech** [comment]
@SaveTheAles @xhipster 
- created gmail cybercongress42 -> service email
- created medium, with new mail
- changed twitter to new email
- created medium, with new email
- created golos accounts
- created steem accounts
all credentials  saved keybase cybercongress private folder

@xhipster do you owner of cybernode account in golos?

**Comment by SaveTheAles** [comment]
https://github.com/cybercongress/congress/blob/master/Processes/blogs_processes.md
